Repository kyuuuu-77/Application, pull requests merged in 2024-10, with the labels that each got.

#6 Pull Request
  app/src/main/res/layout/custom_dialog_battery.xml
  app/src/main/res/layout/password_main.xml
Labels: enhancement

#7 Pull Request
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/arduino/Application/MainActivity.java
  app/src/main/java/com/arduino/Application/ui/bagDrop/BagDropFragment.java
  app/src/main/java/com/arduino/Application/ui/find/FindFragment.java
  app/src/main/java/com/arduino/Application/ui/home/HomeFragment.java
  app/src/main/java/com/arduino/Application/ui/home/HomeViewModel.java
  app/src/main/java/com/arduino/Application/ui/info/InfoFragment.java
  app/src/main/java/com/arduino/Application/ui/weight/WeightFragment.java
  app/src/main/res/drawable/home_lock_off.xml
  app/src/main/res/drawable/home_lock_on.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: bug

#8 layout-edit
  app/src/main/res/layout/custom_dialog_battery.xml
  app/src/main/res/layout/password_main.xml
  app/src/main/res/values/strings.xml
Labels: bug

#10 hotfix
  app/src/main/java/com/arduino/Application/MainActivity.java
  app/src/main/java/com/arduino/Application/ui/find/FindFragment.java
  app/src/main/java/com/arduino/Application/ui/home/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#15 bug fixed
  app/src/main/java/com/arduino/Application/ui/bagDrop/BagDropFragment.java
  app/src/main/res/layout/custom_dialog_time.xml
Labels: bug

#17 bug hotfix and lock function added
  README.md
  app/build.gradle.kts
  app/src/main/java/com/arduino/Application/MainActivity.java
  app/src/main/java/com/arduino/Application/ui/bagDrop/BagDropFragment.java
  app/src/main/java/com/arduino/Application/ui/find/FindFragment.java
  app/src/main/java/com/arduino/Application/ui/home/HomeFragment.java
  app/src/main/java/com/arduino/Application/ui/info/InfoFragment.java
  app/src/main/java/com/arduino/Application/ui/lock/LockFragment.java
  app/src/main/java/com/arduino/Application/ui/weight/WeightFragment.java
  app/src/main/res/drawable/home_auth_off.xml
  app/src/main/res/drawable/home_auth_on.xml
  app/src/main/res/drawable/home_lock_off.xml
  app/src/main/res/drawable/lock_lock.xml
  app/src/main/res/layout/custom_dialog.xml
  app/src/main/res/layout/custom_dialog_auth.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_lock.xml
  app/src/main/res/raw/bell.wav
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#18 Version 1.30 updated
  README.md
  app/build.gradle.kts
  app/src/main/java/com/arduino/Application/MainActivity.java
  app/src/main/java/com/arduino/Application/ui/bagDrop/BagDropFragment.java
  app/src/main/java/com/arduino/Application/ui/find/FindFragment.java
  app/src/main/java/com/arduino/Application/ui/home/HomeFragment.java
  app/src/main/java/com/arduino/Application/ui/info/InfoFragment.java
  app/src/main/java/com/arduino/Application/ui/lock/LockFragment.java
  app/src/main/java/com/arduino/Application/ui/lock/LockViewModel.java
  app/src/main/java/com/arduino/Application/ui/weight/WeightFragment.java
  app/src/main/res/drawable/home_auth_off.xml
  app/src/main/res/drawable/home_auth_on.xml
  app/src/main/res/drawable/home_lock_off.xml
  app/src/main/res/drawable/ic_menu_lock.xml
  app/src/main/res/drawable/lock_lock.xml
  app/src/main/res/layout/custom_dialog.xml
  app/src/main/res/layout/custom_dialog_auth.xml
  app/src/main/res/layout/custom_dialog_time.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_lock.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/raw/bell.wav
  app/src/main/res/raw/lock_off.json
  app/src/main/res/raw/lock_on.json
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#19 Bug fix and improvement
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arduino/Application/MainActivity.java
  app/src/main/java/com/arduino/Application/ui/bagDrop/BagDropFragment.java
  app/src/main/java/com/arduino/Application/ui/find/FindFragment.java
  app/src/main/java/com/arduino/Application/ui/lock/LockFragment.java
  app/src/main/java/com/arduino/Application/ui/weight/WeightFragment.java
  app/src/main/res/drawable/app_info_icon.xml
  app/src/main/res/drawable/background_red.xml
  app/src/main/res/layout/custom_dialog_info.xml
  app/src/main/res/layout/fragment_bagdrop.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#20 development finished
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arduino/Application/MainActivity.java
  app/src/main/java/com/arduino/Application/ui/bagDrop/BagDropFragment.java
  app/src/main/java/com/arduino/Application/ui/find/FindFragment.java
  app/src/main/java/com/arduino/Application/ui/lock/LockFragment.java
  app/src/main/java/com/arduino/Application/ui/weight/WeightFragment.java
  app/src/main/res/drawable/app_info_icon.xml
  app/src/main/res/drawable/background_red.xml
  app/src/main/res/layout/custom_dialog_info.xml
  app/src/main/res/layout/fragment_bagdrop.xml
  app/src/main/res/values/strings.xml
  lang/README_EN.md
  lang/README_JA.md
Labels: bug, documentation, enhancement
